// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVXuBFerfqrX3UVhWqhA06CQW0iWSqaEY',
    appId: '1:1066005121147:web:d8d7012f1ce24354c03ade',
    messagingSenderId: '1066005121147',
    projectId: 'habitforge-60e2e',
    authDomain: 'habitforge-60e2e.firebaseapp.com',
    storageBucket: 'habitforge-60e2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJU_Az1NC9hgxgtGryz0fQJxyrBHlwMOM',
    appId: '1:1066005121147:android:08dd4b5939e1ed10c03ade',
    messagingSenderId: '1066005121147',
    projectId: 'habitforge-60e2e',
    storageBucket: 'habitforge-60e2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZpOWLykAeeA4xktpYtpPVYfzD3L2ZbN8',
    appId: '1:1066005121147:ios:c61eddea81f54c3fc03ade',
    messagingSenderId: '1066005121147',
    projectId: 'habitforge-60e2e',
    storageBucket: 'habitforge-60e2e.firebasestorage.app',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVXuBFerfqrX3UVhWqhA06CQW0iWSqaEY',
    appId: '1:1066005121147:web:b147199292418e37c03ade',
    messagingSenderId: '1066005121147',
    projectId: 'habitforge-60e2e',
    authDomain: 'habitforge-60e2e.firebaseapp.com',
    storageBucket: 'habitforge-60e2e.firebasestorage.app',
  );
}
